BLOGSHOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
'''Urls to blog'''
# Django
from django.urls import path
# Views
from . import views

app_name = 'blog'

urlpatterns = [
    path(route='',
         view=views.PostMainPage.as_view(),
         name='main_page'),

    path(route='blog/search/',
         view=views.search,
         name='post_search'),

    path(route='blog/pasive/',
         view=views.PasiveView.as_view(),
         name='pasive'),

    path(route='blog/active/',
         view=views.ActiveView.as_view(),
         name='active'),

    path(route='blog/diode/<slug>/',
         view=views.DiodesDetailView.as_view(),
         name='details'),

    path(route='blog/transitor/<slug>/',
         view=views.TransistorDetailView.as_view(),
         name='details_t'),

    path(route='blog/post/<slug>/',
         view=views.PostDetailView.as_view(),
         name='post_details'),
]

templates/component/component_mainpage.html
  	{% load blog_tags %}
  	<h1>
      {{ component.title }}
    </h1>        
    <img class="center-image" src="{{ component.image.url }}" alt="{{ component.title }}">
    <p class="date">
      {{ component.description|markdown }}
    </p>

    {% if component.datasheet %}
    	<hi>Datasheet</hi>
    	<a href="{{ component.datasheet }}" target="blank">Datasheet</a>
    {% endif %}

templates/component/form_search.html
<div class="form_search">
    <form method="GET" action="{% url "blog:post_search" %}">
    {{ form.as_p }}
    <input type="submit" value="Buscar">
    </form>
</div>

templates/component/form_search2.html
<div class="form_search2">
<form method="GET" action="{% url "blog:post_search" %}">
    {{ form.as_p }}
    <input type="submit" value="Buscar">
</form> 
</div>

templates/component/general_component_main.html
{% load blog_tags %}
<li style="margin-top: 8px">
        <a href="{% url "blog:details" component.slug %}">{{ component.title }} </a>
</li>

templates/component/general_component_transistor.html
{% load blog_tags %}
<li style="margin-top: 8px">
        <a href="{% url "blog:details_t" component.slug %}">{{ component.title }} </a>
</li>