BLOGSHOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
'''Urls to blog'''
# Django
from django.urls import path
# Views
from . import views

app_name = 'blog'

urlpatterns = [
    path(route='',
         view=views.PostMainPage.as_view(),
         name='main_page'),

    path(route='blog/search/',
         view=views.search,
         name='post_search'),

    path(route='blog/pasive/',
         view=views.PasiveView.as_view(),
         name='pasive'),

    path(route='blog/active/',
         view=views.ActiveView.as_view(),
         name='active'),

    path(route='blog/diode/<slug>/',
         view=views.DiodesDetailView.as_view(),
         name='details'),

    path(route='blog/transitor/<slug>/',
         view=views.TransistorDetailView.as_view(),
         name='details_t'),

    path(route='blog/post/<slug>/',
         view=views.PostDetailView.as_view(),
         name='post_details'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link href="{%static "css/blog.css" %}" rel="stylesheet">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
  </script>
  </head>

  <body>
    <div id="content">
      {% include "navbar.html" %} {% block content%} {% endblock %}
    </div>
    <div id="sidebar">
      {% include "component/form_search.html" %}
      {% block sidebar %} 

      {% endblock%}
    </div>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function () {
        $("ul.navp li a:first").addClass("active-panel");
        $(".info article").hide();
        $(".info article:first").show();
        $(".sidebar-info .side-infor").show();
        $(".sidebar-info .side-infoc").hide();
        $(".sidebar-info .side-infod").hide();

        $("ul.navp li a").click(function () {
          $("ul.navp li a").removeClass("active-panel");
          $(this).addClass("active-panel");
          $(".info article").hide();
          $(".sidebar-info article").hide();

          var activeTab = $(this).attr("href");
          console.log(activeTab);
          $(activeTab).show();
          if (activeTab == "#tab1") {
            $(".sidebar-info .side-infor").show();
            $(".sidebar-info .side-infoc").hide();
            $(".sidebar-info .side-infod").hide();
            $(".infos article:first").show();
          } else {
            $(".sidebar-info .side-infor").hide();
          }

          if (activeTab == "#tab2") {
            $(".sidebar-info .side-infoc").show();
            $(".sidebar-info .side-infor").hide();
            $(".sidebar-info .side-infod").hide();
            $(".infos article#ctab0").show();
          } else {
            $(".sidebar-info .side-infoc").hide();
          }

          if (activeTab == "#tab3") {
            $(".sidebar-info .side-infod").show();
            $(".sidebar-info .side-infor").hide();
            $(".sidebar-info .side-infoc").hide();
            $(".infos article#dtab0").show();
          } else {
            $(".sidebar-info .side-infod").hide();
          }

          return false;
        });

        $("ul.navp-sub li a:first").addClass("active-panel-s");
        $(".infos article").hide();
        $(".infos article:first").show();

        $("ul.navp-sub li a").click(function () {
          $("ul.navp-sub li a").removeClass("active-panel-s");
          $(this).addClass("active-panel");
          $(".infos article").hide();

          var activeTab2 = $(this).attr("href");
          console.log(activeTab2);
          $(activeTab2).show();
          return false;
        });
      });
    </script>
  </body>
</html>

templates/navbar.html
{% if component %}
	<h1>{{ component.title }}</h1>
{% elif devise %}	
	<h1>{{ devise }}</h1>
{% else %}
	<h1>Electroshopck</h1>
{% endif %}

<div>
<nav class="navbar">
	<ul>
		<a href="{% url "blog:main_page" %}" class="a-nav">Home</a>
		<h6 class="hide">Principal</h6>
	</ul>
	<ul>
		<a href="{% url "blog:pasive" %}" class="a-nav">Pasivos</a>
		<h6 class="hide">Dispositivos Pasivos</h6>
	</ul>
	<ul>
		<a href="{% url "blog:active" %}" class="a-nav">Activos</a>
		<h6 class="hide">Dispositivos Activos</h6>
	</ul>
</nav>
{% include "component/form_search2.html" %}
</div>








 