BLOGSHOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
'''Urls to blog'''
# Django
from django.urls import path
# Views
from . import views

app_name = 'blog'

urlpatterns = [
    path(route='',
         view=views.PostMainPage.as_view(),
         name='main_page'),

    path(route='blog/search/',
         view=views.search,
         name='post_search'),

    path(route='blog/pasive/',
         view=views.PasiveView.as_view(),
         name='pasive'),

    path(route='blog/active/',
         view=views.ActiveView.as_view(),
         name='active'),

    path(route='blog/diode/<slug>/',
         view=views.DiodesDetailView.as_view(),
         name='details'),

    path(route='blog/transitor/<slug>/',
         view=views.TransistorDetailView.as_view(),
         name='details_t'),

    path(route='blog/post/<slug>/',
         view=views.PostDetailView.as_view(),
         name='post_details'),
]

templates/post/list_post.html
{% load blog_tags %}

<a href="{% url "blog:post_details" post.slug %}">
    <div>
        <h4 class ="post-title">
            {{ post.title }}
        </h4>
        <img class="center-image-posts" src="{{ post.image.url }}" alt="{{ post.title }}">
        <div class="date">
            {{ post.body|truncatewords_html:30 }}
        </div>
    </div>
</a>

templates/post/list_post_side.html
<div class="side-bar-posts">
<a href="{% url "blog:post_details" post.slug %}">
    <h3 class="sidebar_color">
        {{ post.title }}
    </h3>
    <p class="date">
        {{ post.body|truncatewords_html:10 }}
    </p>
</a>
</div>

templates/post/post_detail.html
{% extends "base.html" %}
{% load blog_tags %}

{% block title %}
	{{ component.title }}
{% endblock %}

{% block content %}
    <h1>
        {{ post.title }}
    </h1>        
    <img class="center-image-2" src="{{ post.image.url }}" alt="{{ post.title }}">
    <p class="date">
        {{ post.body|markdown }}
    </p>
	

{% endblock %}

{% block sidebar %}
<h2 style="text-align: center;">
</h2>
		<!-- <img class="center-image-3" src="{{ component.image.url }}" alt="{{ component.title }}">

		<h3 class="sidebar_color">Componentes similares</h3>
		<h5> {{ component.similar_components }}</h5>

		<h3 class="sidebar_color">Aplicaciones</h3>
		<h5> {{ component.aplications|markdown }}</h5>


		<a href="{{ component.datasheet }}" target="blank">Datasheet</a> -->

{% endblock %}